BEGIN;

\encoding UNICODE;

DELETE FROM movies;
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('劇場版「鬼滅の刃」無限列車編',  '大正時代の日本。鬼に家族を皆殺しにされ、生き残った妹の禰豆子も鬼に変貌してしまった炭治郎は、妹を人間に戻し、家族を殺した鬼を討つため、鬼狩りの道を進む決意をする。蝶屋敷での修業を終えた炭治郎たちは、短期間のうちに40人以上もの人が行方不明になっているという無限列車に到着する。炭治郎、禰豆子、善逸、伊之助は、鬼殺隊最強の剣士の1人、煉獄杏寿郎と合流し、無限列車の中で鬼と立ち向かう。', '外崎春雄', ' 【声の出演】花江夏樹/鬼頭明里/下野紘/松岡禎丞/日野聡 ほか', 117,  'https://109cinemas.net/media/W1siZiIsIjIwMjEvMDcvMTUvMTZfNTFfMDRfMzM2X18uanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/メイン.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('東京リベンジャーズ',  '負け犬フリータータケミチの元恋人ヒナタが殺された。事件を知った翌日、タケミチは駅のホームから転落、目覚めた先はなんと10年前――負け犬人生を歩むきっかけとなった最悪の高校時代にタイムリープしてしまった。もう一度繰り返される、あの頃。最悪の過去でようやく見つけたヒナタを救う唯一の方法は、ヤクザも恐れる危険な組織“東京卍會”を消滅させること。熱い仲間たちとの出会いの中で、ヒナタを救うため、逃げ続けた人生を変えるため、タケミチは弱虫だった“過去”の人生にリベンジし、“今”を変えられるのか？', '英勉',  '北村匠海/山田裕貴/杉野遥亮/今田美桜/鈴木伸之/眞栄田郷敦/清水尋也/磯村勇斗/間宮祥太朗/吉沢亮 ほか', 120,  'https://109cinemas.net/media/W1siZiIsIjIwMjEvMDYvMDQvMTFfMzJfNTlfNTIyX0pQX3Bob3RvbWFpbl9yZXZfVFIuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/JP-photomain-rev-TR.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('今夜、世界からこの恋が消えても',  '僕の人生は無色透明だった。真織と出会うまでは――。クラスメイトに流されるまま、彼女に仕掛けた嘘の告白。しかし彼女は“お互い絶対に本気で好きにならないこと”を条件にその告白を受け入れた。そうして始まった偽りの恋。やがてそれが偽りとは言えなくなったころ――僕は知る。「病気なんだ私。前向性健忘って言って、夜眠ると忘れちゃうの。一日にあったこと、全部」彼女はその日の出来事を日記に記録して、朝目覚めたときに復習することで何とか記憶をつなぎとめていた。その日ごとに記憶を失ってしまう彼女のために、日記が楽しい出来事で溢れるようにと、一日限りの恋を積み重ねていく日々。しかし僕には真織に伝えていないことがひとつだけある。', '三木孝浩',  '道枝駿佑(なにわ男子)/福本莉子/古川琴音/前田航基/西垣匠/松本穂香/野間口徹/野波麻帆/水野真紀/萩原聖人 ほか', 121,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDYvMjQvMTlfNTJfMDhfNDE0X18uanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/『セカコイ』メインビジュアル.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('名探偵コナン ハロウィンの花嫁',  'ハロウィンシーズンで賑わう東京渋谷。渋谷ヒカリエでとある結婚式が執り行われていた。そこには、ウェディングドレスに身を包んだ警視庁・佐藤刑事の花嫁姿が。コナン達招待客が見守る中、突然乱入してきた暴漢が襲い掛かり、守ろうとした高木刑事の身に危機が―!? 事態は収束し高木は無事だったが、佐藤の瞳には、3年前の連続爆破事件で、想いを寄せていた松田刑事が殉職してしまった際に見えた死神のイメージが、高木に重なって見えていた。時を同じくして、その連続爆破事件の犯人が脱獄。果たしてこれは偶然なのか？公安警察の降谷零（安室透）が、同期である松田刑事を葬った因縁の相手を追い詰めるが、そこに現れた謎の仮装の人物に、首輪爆弾をつけられてしまう。首輪爆弾解除のために安室が潜伏している地下シェルターを訪れたコナンは、3年前に今は亡き警察学校時代の同期メンバー達と正体不明の仮装爆弾犯「プラーミャ」と渋谷で遭遇した事件の話を聞く。やがて、捜査を進めるコナン達を狙う不穏な影が―。火が灯された運命のスクランブル。いま、祝祭のハロウィンが狂乱の夜行へと変貌する―', '満仲 勧',  ' 【声の出演】高山みなみ/山崎和佳奈/小山力也/古谷徹/高木渉/湯屋敦子/白石麻衣 ほか', 110,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDMvMDcvMTZfMzBfMjhfNjAxX18uanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/メイン.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('新海誠IMAX映画祭「天気の子」',  '「あの光の中に、行ってみたかった」高1の夏。離島から家出し、東京にやってきた帆高。しかし生活はすぐに困窮し、孤独な日々の果てにようやく見つけた仕事は、怪しげなオカルト雑誌のライター業だった。彼のこれからを示唆するかのように、連日降り続ける雨。そんな中、雑踏ひしめく都会の片隅で、帆高は一人の少女に出会う。ある事情を抱え、弟とふたりで明るくたくましく暮らすその少女・陽菜。彼女には、不思議な能力があった。', '新海誠',  ' 【声の出演】醍醐虎汰朗/森七菜/本田翼/吉柳咲良/平泉成/梶裕貴/倍賞千恵子/小栗旬 ほか', 113,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDkvMTUvMTlfMTNfNTdfMTA0X18uanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/天気の子.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('新海誠IMAX映画祭「君の名は。」',  '千年ぶりとなる彗星の来訪を一か月後に控えた日本。山深い田舎町に暮らす女子高校生・三葉は憂鬱な毎日を過ごしていた。町長である父の選挙運動に、家系の神社の古き風習。小さく狭い町で、周囲の目が余計に気になる年頃だけに、都会への憧れを強くするばかり。「来世は東京のイケメン男子にしてくださーい！！！」そんなある日、自分が男の子になる夢を見る。', '新海誠',  ' 【声の出演】神木隆之介/上白石萌音/成田凌/悠木碧/島﨑信長/石川界人/谷花音/長澤まさみ/市原悦子 ほか', 107,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDkvMTUvMTlfMTdfMzJfMzA2X18uanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/君の名は.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('新海誠IMAX映画祭「秒速5センチメートル」',  'ひかれあっていた男女の時間と距離による変化を全3話の短編で描いた連作アニメーション。互いに思いあっていた貴樹と明里は、小学校卒業と同時に明里の引越しで離ればなれになってしまう。中学生になり、明里からの手紙が届いたことをきっかけに、貴樹は明里に会いにいくことを決意する（第1話「桜花抄」）。やがて貴樹も中学の半ばで東京から引越し、遠く離れた鹿児島の離島で高校生生活を送っていた。同級生の花苗は、ほかの人とはどこか違う貴樹をずっと思い続けていたが……（第2話「コスモナウト」）。社会人になり、東京でSEとして働く貴樹。付き合った女性とも心を通わせることができず別れてしまい、やがて会社も辞めてしまう。季節がめぐり春が訪れると、貴樹は道端である女性に気づく（第3話「秒速5センチメートル」）。', '新海誠', ' 【声の出演】水橋研二/近藤好美/尾上綾華/花村怜美 ほか', 63,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDkvMDcvMTFfMTdfMzlfMTEwX18uanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/秒速.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('すずめの戸締まり',  '扉の向こうには、すべての時間があった―。『君の名は。』『天気の子』の新海誠監督最新作、ついに始動ー。九州の静かな町で暮らす17歳の少女・鈴芽（すずめ）は、「扉を探してるんだ」という旅の青年に出会う。彼の後を追うすずめが山中の廃墟で見つけたのは、まるで、そこだけが崩壊から取り残されたようにぽつんとたたずむ、古ぼけた扉。なにかに引き寄せられるように、すずめは扉に手を伸ばすが…やがて、日本各地で次々に開き始める扉。その向こう側からは災いが訪れてしまうため、開いた扉は閉めなければいけないのだという。―――星と、夕陽と、朝の空と。迷い込んだその場所には、すべての時間が溶けあったような、空があった―――不思議な扉に導かれ、すずめの“戸締まりの旅”がはじまる。', '新海誠',  ' 【声の出演】原菜乃華/松村北斗(SixTONES)/深津絵里/染谷将太/伊藤沙莉/花瀬琴音/花澤香菜/松本白鸚 ほか', 122,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDkvMjgvMTJfNDVfNDlfNTc2X19XRUJfLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/（WEB用）メインカット.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('ハニーレモンソーダ',  '中学時代“石”と呼ばれていた自分を変えるため、自由な高校に入学した石森羽花。そこで出会ったのはレモン色の髪をした三浦界。実は彼こそが、その高校を選んだ理由だった。クールで自由奔放、基本塩対応なのに人気者の界。彼はなぜか自分を “石森係” と呼び、羽花の世話を焼いてくれるように。距離が近づいた二人は想いを伝え合い、幸せな毎日を送っていたが実は、界には羽花に伝えられていない秘密があって…', '神徳幸治',  'ラウール(Snow Man)/吉川愛/堀田真由/濱田龍臣/坂東龍汰/岡本夏美 ほか', 111,  'https://109cinemas.net/media/W1siZiIsIjIwMjEvMDYvMDQvMTFfMjZfMjVfOTI3X19tYWluQV9XRUJfaGxzX3dpZGVfcHViX1JHQi5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/★mainA紙WEB媒体用★hls_wide_pub_RGB.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('劇場版 呪術廻戦0',  '幼少のころ、幼なじみの祈本里香を交通事故により目の前で失った乙骨憂太。「約束だよ 里香と憂太は大人になったら結婚するの」怨霊と化した里香の呪いに苦しみ、自身の死を望む乙骨だったが、最強の呪術師・五条悟によって、呪術高専に迎え入れられた。そして、同級生の禪院真希・狗巻 棘・パンダと出会い、乙骨はある決意をする。「生きてていいって自信が欲しいんだ」「僕は呪術高専で里香ちゃんの呪いを解きます」一方、乙骨たちの前にかつて一般人を大量虐殺し高専を追放された最悪の呪詛師・夏油 傑が現れる。「来たる12月24日 我々は百鬼夜行を行う」 呪術師だけの楽園を標榜する夏油は、非術師を殲滅させんと、ついに新宿・京都に千の呪いを放ち―― 果たして、乙骨は夏油を止められるのか、そして、里香の解呪の行方は‥‥。', '朴性厚',  ' 【声の出演】緒方恵美/花澤香菜/小松未可子/内山昂輝/関智一/中村悠一/櫻井孝宏 ほか', 105,  'https://109cinemas.net/media/W1siZiIsIjIwMjEvMTEvMTcvMTRfNDFfMTRfODA1X0pKS1NNX3B1YmN1dF92aXN1YWwuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/JJKSM_pubcut_visual.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('なのに、千輝くんが甘すぎる。',  '人生初の告白に見事に玉砕した高校2年生の失恋女子・真綾。親友の小原知花に慰められるも、落ち込んでいるところを陸上部のエースで学校一のイケメン男子・千輝くんに見られてしまう。モテモテなのに周囲には塩対応な千輝くんが、なぜか真綾に提案したのは、なんと“片想いごっこ”!「好きな人、無理に探すくらいなら、俺に片想いすれば？」。 片想いごっこの条件は、絶対に好きにならないことと、まわりにバレないこと。好きになってはいけない約束なのに、自分にだけ優しくて甘すぎる千輝くんに、真綾の気持ちは次第に揺れ動いていく…。そんな中、真綾に密かに想いを寄せるクラスメイトの手塚に、秘密の関係を知られてしまい…。 千輝、真綾の片想いごっこの行方は――？！', '新城毅彦',  ' 高橋恭平(なにわ男子)/畑 芽育/板垣李光人/莉子/曽田陵介/中島瑠菜/箭内夢菜/鈴木美羽 ほか', 98,  'https://109cinemas.net/media/W1siZiIsIjIwMjMvMDIvMjAvMjBfNDhfNDZfNTgxX18uanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/★メイン.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('劇場版 からかい上手の高木さん',     '慣れ親しんだ学び舎との別れ、進路や将来のこと…。少しずつ大人の階段をのぼり始める中学3年生の夏の1ページに刻まれる、ふたりの青春模様が、原作者・山本崇一朗監修の下、TVシリーズと同じスタッフ陣によって瑞々しく丁寧に紡がれる。これは、ひと夏に起こる、ちいさくて、やさしい青春物語―。とある中学校、隣の席になった女の子・高木さんに、何かとからかわれる男の子・西片。どうにかして高木さんをからかい返そうと日々奮闘する西片だが、いつも高木さんに見透かされてしまう―。 ', '赤城博昭',  ' 【声の出演】高橋李依/梶裕貴/小原好美/M・A・O/小倉唯/落合福嗣/岡本信彦/内山昂輝/悠木碧/内田雄馬/岩井ことり/田所陽向/水瀬いのり/戸松遥 ほか', 73,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDUvMTcvMTVfNTdfMzJfMjA5X18yXy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/【高木さん】特報場面写%20(2).jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('バズ・ライトイヤー',  '「トイ・ストーリー」で誰よりも仲間思いのバズ・ライトイヤーの、知られざるルーツを描く感動のファンタジー・アドベンチャー。有能なスペース・レンジャーのバズは、自分の力を過信したために、1200人もの乗組員と共に危険な惑星に不時着してしまう。地球に帰還するため、バズは猫型の友だちロボットのソックスと共に不可能なミッションに挑む。その行く手には、ずっと孤独だったバズの人生を変える個性豊かな仲間たちと、思いもよらぬ“敵”が待ち受けていた──', 'アンガス・マクレーン',  ' 【声の出演】鈴木亮平/今田美桜/山内健司(かまいたち)/りょう/三木眞一郎/磯辺万沙子/銀河万丈/沢城みゆき ほか', 105,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDYvMTAvMTlfNDhfNDJfODAyX18uanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/メイン.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('前科者',  '罪を犯した者、非行のある者の更生に寄り添う国家公務員、保護司。保護司を始めて3年の阿川佳代は仕事にやりがいを感じ、様々な「前科者」のために奔走していた。そんな中、佳代が担当している物静かな工藤誠は更生を絵に描いたような人物で、佳代は誠が社会人として自立する日は近いと楽しみにしていた。しかし、誠は忽然と姿を消し、再び警察に追われる身に。一方その頃、連続殺人事件が発生。捜査が進むにつれ佳代の壮絶な過去や、若くして保護司という仕事を選んだ理由も次第に明らかになっていき――。', '岸善幸',  '有村架純/磯村勇斗/若葉竜也/マキタスポーツ/石橋静河/北村有起哉/宇野祥平/リリー・フランキー/木村多江/森田剛 ほか', 133,  'https://109cinemas.net/media/W1siZiIsIjIwMjEvMTIvMjAvMTBfNDBfMDdfODEyX19IUF9TTlNfLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/★メイン%E3%80%80※劇場HP・劇場SNS・ラインナップチラシ以外での使時は要確認.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('バイオハザード：ウェルカム・トゥ・ラクーンシティ',  'アメリカ合衆国中西部に位置するラクーンシティ。自然豊かなこの街の郊外に以前は製薬会社アンブレラ社の工場が存在したが、今はその殆どの施設は移転してしまっている。 このアンブレラ社が秘密裏に研究開発を進めていた“何か”が街の住民達に大きな健康被害を与えているとのメッセージを受け取ったクレア。 ラクーンシティの施設で育ったクレアは、その真実を突き止めるべく、R.P.D.(ラクーン市警)で特殊部隊=S.T.A.R.S.の隊員である兄・クリスのもとを訪ねる。クレアはクリスにこの事実を訴えるも「お前は昔から陰謀論を持ち出すが、デタラメだ」と取り合ってくれない。 しかしその時、街中に大音量のサイレンが鳴り響く。 アンブレラ社から住民に自宅で待機するよう警報が発せられたのだ。 クリスは急ぎ署に出向き、S.T.A.R.S.の隊員である、ジル、ウェスカーと共に、郊外にあるスペンサー邸で消息を絶った同僚を捜索する為、ヘリコプターで出動する－。 一方、クレアはクリスを追いかけR.P.D.に－。 しかし、既に住民達の身体には変化が起き始めていた。 その皮膚は腐乱し、口や目から血液が流れ落ち、死体の様な状態にも関わらず、人肉を欲し彷徨うゾンビと化したのだ。 スペンサー邸ではクリス達の壮絶なサバイバルが繰り広げられ、R.P.D.内でも、クレアそして新人警官のレオンに、ゾンビ達が襲い掛かる。', 'ヨハネス・ロバーツ',  'カヤ・スコデラリオ/ハナ・ジョン＝カーメン/ロビー・アメル/トム・ホッパー/アヴァン・ジョーギア/ドナル・ローグ/ニール・マクドノー ほか', 107,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDEvMTIvMTRfMjJfMDlfMzA3X19fX19EYXkzNl9SZXNpZGVudEV2aWxfNzUwMF9yLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/メイン_トリミング_Day36_ResidentEvil_7500_r.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('キングダム2 遥かなる大地へ',  '時は紀元前、中国春秋戦国時代を舞台に、天下の大将軍になるという夢を抱く戦災孤児の少年・信と、中華統一を目指す若き王・嬴政（後の秦の始皇帝）を壮大なスケールで描く漫画「キングダム」（原泰久/集英社）。2019年に映画『キングダム』が封切られると、邦画史上最大級のスケールで描かれた本格エンターテインメント超大作として多くのファンの支持を獲得し、興行収入57.3億円を突破。前作から３年の時を経て、更なるスケールへとパワーアップを果たし、スクリーンに帰ってくる！！戦災孤児として育った信は、王弟のクーデターにより玉座を追われた若き王・嬴政に出会う。天下の大将軍になると一緒に誓いながらも死別した幼馴染の漂とうり二つの国王に力を貸し、みごと内乱を鎮圧。玉座を奪還することに成功した。しかし、これは途方もなき戦いの始まりに過ぎなかった――', '佐藤信介',  '山﨑賢人/吉沢亮/橋本環奈/清野菜名/満島真之介/岡山天音/三浦貴大/濱津隆之/真壁刀義/山本千尋/豊川悦司/髙嶋政宏/要潤/加藤雅也/高橋努/渋川清彦/平山祐介/玉木宏/小澤征悦/佐藤浩市 ほか', 134,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDYvMjQvMTlfNTFfMzBfOTc5X18uanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/横ビジュアル.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('タイタニック:ジェームズ・キャメロン25周年3Dリマスター',  '1912年、処女航海に出た豪華客船タイタニック号。新天地アメリカを目指す画家志望の青年ジャックと上流階級の娘ローズは船上で運命的な出会いを果たす。身分違いの恋を乗り越え強い絆で結ばれていく2人。しかし不沈を誇っていた豪華客船は皮肉な運命に見舞われる‥‥。', 'ジェームズ・キャメロン',  'レオナルド・ディカプリオ/ケイト・ウィンスレット/ビリー・ゼーン/キャシー・ベイツ/ビル・パクストン ほか', 195,  'https://109cinemas.net/media/W1siZiIsIjIwMjMvMDEvMjAvMThfMDdfNTZfODQ4X18xXy5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/メイン%20(1).jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('ONE PIECE FILM RED',  '総合プロデューサー:尾田栄一郎で贈る”FILM“ シリーズ第4弾!物語の鍵を握るのは… ”歌声”と”赤髪”。 世界で最も愛されている歌手、ウタ。素性を隠したまま発信するその歌声は“別次元”と評されていた。そんな彼女が初めて公の前に姿を現すライブが開催される。色めき立つ海賊たち、目を光らせる海軍、そして何も知らずにただ彼女の歌声を楽しみにきたルフィ率いる麦わらの一味たち、ありとあらゆるウタファンが会場を埋め尽くす中、今まさに全世界待望の歌声が響き渡ろうとしていた。物語は、彼女が“シャンクスの娘”という衝撃の事実から動き出す―。', '谷口悟朗',  '【声の出演】田中真弓/中井和哉/岡村明美/山口勝平/平田広明/大谷育江/山口由里子/矢尾一樹/チョー/宝亀克寿/名塚佳織/Ado/津田健次郎/池田秀一 ほか', 115,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDYvMjQvMTlfNTNfNDVfNTEyX18uanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/メイン①.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('映画『五等分の花嫁』',  '「落第寸前」「勉強嫌い」の美少女五つ子を、アルバイト家庭教師として「卒業」まで導くことになった風太郎。これまでの努力が実を結び、高校3年生に進級することができた五つ子は、修学旅行も無事に終わり「卒業」に向けてそれぞれが将来を見据えていくことに。共に過ごす中で風太郎への恋心を自覚した五つ子と、段々と惹かれていく風太郎。風太郎と五つ子の恋の行方はいかに…!? そして未来の花嫁は果たして……。', '神保昌登',  '【声の出演】松岡禎丞/花澤香菜/竹達彩奈/伊藤美来/佐倉綾音/水瀬いのり ほか', 136,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDQvMDgvMTdfNTVfNDhfMjc5X19fX0tWX19fLmpwZyJdLFsicCIsInRodW1iIiwiNjQweDM2MCJdXQ/五等分の花嫁_第二弾KVポスター_劇場用メインカット.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('SING/シング:ネクストステージ',  'バスター率いるロジータやグンターらは地元で人気を博し、ニュー・ムーン・シアターは連日満席！しかしバスターは華やかで煌びやかなエンターテイメントの聖地レッド・ショア・シティにあるクリスタル・タワー・シアターで新しいショーを披露するという大きな夢を抱いていた。人生最大の夢の舞台でバスターたちの新たな挑戦が始まる！', 'ガース・ジェニングス',  '【声の出演】内村光良/MISIA/長澤まさみ/大橋卓弥(スキマスイッチ)/斎藤司(トレンディエンジェル)/ジェシー(SixTONES)/アイナ・ジ・エンド/akane/坂本真綾/田中真弓/大地真央/稲葉浩志 ほか', 111,  'https://109cinemas.net/media/W1siZiIsIjIwMjIvMDIvMTUvMTJfNDdfMjlfMTg1X1RNMl9TRzJfSU5UTF8xU0hUX1JFRFNIT1JFX0NJVFlfQ01ZS19yZTIuanBnIl0sWyJwIiwidGh1bWIiLCI2NDB4MzYwIl1d/TM2_SG2_INTL_1SHT_REDSHORE_CITY_CMYK_re2.jpg', current_timestamp, current_timestamp);
INSERT INTO movies (title, description, director, actors, duration, thumbnail, created_at, updated_at) VALUES ('スパイダーマン：ノー・ウェイ・ホーム',  '世界中にスパイダーマンであることを明かされたピーター・パーカーに時空を超えて集結した過去シリーズのヴィラン達が襲い掛かる――。', 'ジョン・ワッツ',  ' トム・ホランド/ゼンデイヤ/ベネディクト・カンバーバッチ/ジョン・ファヴロー/ジェイコブ・バタロン/マリサ・トメイ/アルフレッド・モリーナ ほか', 149,  'https://109cinemas.net/media/W1siZiIsIjIwMjEvMTIvMDgvMTFfMThfNDFfODk5X19fU01OV0hfcHViY3V0XzAxQS5qcGciXSxbInAiLCJ0aHVtYiIsIjY0MHgzNjAiXV0/---_SMNWH_pubcut_01A.jpg', current_timestamp, current_timestamp);

COMMIT;